- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:

    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Deploy Zomato Docker Container
      docker_container:
        name: zomatoapp
        image: akankshatech/zomatoapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "8084:3000"
